"use client";
// GENERATED by `pnpm hitl:sync` from hitl-ai2/packages/ui (@hitl-kit/ui). Do not edit; edit the package.

import { useEffect, useRef, useState, type ReactNode } from "react";
import {
  AlertCircle,
  Check,
  ChevronDown,
  ChevronRight,
  HelpCircle,
  Loader2,
  RotateCcw,
  X,
} from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * The pieces every decision surface is built from. Internal to the package:
 * they are not exported, and the registry inlines them into `hitl-shared`.
 *
 * Type inside a card: 11px meta, 12px body, 13px title. Nothing else.
 * Motion: 150ms ease-out on colour, none under reduced motion.
 * Focus: a 2px ring, always visible on keyboard focus, never on click.
 */

export const focusRing =
  "focus:outline-none focus-visible:ring-2 focus-visible:ring-ring";

export const motion =
  "transition-colors duration-150 ease-out motion-reduce:transition-none";

export const btnPrimary = cn(
  "inline-flex items-center gap-1.5 rounded-md bg-muted px-3 py-1.5 text-xs font-medium text-foreground",
  "hover:bg-muted/70 disabled:cursor-not-allowed disabled:opacity-50",
  motion,
  focusRing,
);

export const btnQuiet = cn(
  "inline-flex h-7 items-center gap-1 rounded-md px-2 text-xs text-muted-foreground",
  "hover:bg-muted hover:text-foreground disabled:cursor-not-allowed disabled:opacity-50",
  motion,
  focusRing,
);

export const btnLink = cn(
  "rounded text-[11px] text-muted-foreground underline underline-offset-2",
  "hover:text-foreground",
  motion,
  focusRing,
);

/** The in-button spinner shown while `busy`. */
export function Loader() {
  return (
    <Loader2
      className="h-3 w-3 animate-spin motion-reduce:animate-none"
      aria-hidden="true"
    />
  );
}

export type Tone = "ok" | "bad" | "warn" | "info" | "muted";

export const TONE_TEXT: Record<Tone, string> = {
  ok: "text-[color:var(--accent-emerald)]",
  bad: "text-[color:var(--accent-rose)]",
  warn: "text-[color:var(--accent-amber)]",
  info: "text-[color:var(--accent-blue)]",
  muted: "text-muted-foreground",
};

/** A mono metadata chip. `title` carries the long form for hover and AT. */
export function Chip({
  children,
  title,
  tone = "muted",
  className,
}: {
  children: ReactNode;
  title?: string;
  tone?: Tone;
  className?: string;
}) {
  return (
    <span
      title={title}
      className={cn(
        "rounded bg-muted/60 px-1.5 py-0.5 font-mono text-[11px]",
        tone === "muted" ? "text-muted-foreground" : TONE_TEXT[tone],
        className,
      )}
    >
      {children}
    </span>
  );
}

/** The card frame every surface sits in. */
export function Card({
  children,
  label,
  className,
}: {
  children: ReactNode;
  label: string;
  className?: string;
}) {
  return (
    <div
      role="group"
      aria-label={label}
      className={cn(
        "my-1.5 rounded-xl border border-border bg-card text-xs",
        className,
      )}
    >
      {children}
    </div>
  );
}

/** Heuristic 10: one plain sentence of help under the header. */
export function HelpLine({ text }: { text?: string }) {
  if (!text) return null;
  return (
    <p className="flex items-start gap-1.5 border-b border-border px-3 py-1.5 text-[11px] leading-relaxed text-muted-foreground">
      <HelpCircle className="mt-0.5 h-3 w-3 shrink-0" aria-hidden="true" />
      <span>{text}</span>
    </p>
  );
}

/** Heuristic 9: what went wrong, in words, with the way out beside it. */
export function InlineError({
  message,
  onRetry,
}: {
  message?: string;
  onRetry?: () => void;
}) {
  if (!message) return null;
  return (
    <div
      role="alert"
      className="flex items-start gap-2 border-t border-[color:var(--accent-rose)]/40 bg-[color:var(--accent-rose)]/5 px-3 py-2 text-[11px] leading-relaxed text-[color:var(--accent-rose)]"
    >
      <AlertCircle className="mt-0.5 h-3 w-3 shrink-0" aria-hidden="true" />
      <span className="flex-1">{message}</span>
      {onRetry && (
        <button type="button" onClick={onRetry} className={cn(btnLink, "text-[color:var(--accent-rose)]")}>
          Retry
        </button>
      )}
    </div>
  );
}

/** A disclosure row: chevron, label, optional count. */
export function Disclosure({
  open,
  onToggle,
  controls,
  children,
  className,
}: {
  open: boolean;
  onToggle: () => void;
  controls: string;
  children: ReactNode;
  className?: string;
}) {
  return (
    <button
      type="button"
      onClick={onToggle}
      aria-expanded={open}
      aria-controls={controls}
      className={cn(
        "flex w-full items-center gap-1 px-3 py-1.5 text-left text-muted-foreground hover:text-foreground",
        motion,
        focusRing,
        className,
      )}
    >
      {open ? (
        <ChevronDown className="h-3 w-3" aria-hidden="true" />
      ) : (
        <ChevronRight className="h-3 w-3" aria-hidden="true" />
      )}
      {children}
    </button>
  );
}

export interface DecisionBarProps {
  approveLabel: string;
  rejectLabel?: string;
  /** Omit to hide the abstain option. */
  abstainLabel?: string;
  onApprove: () => void;
  onReject: () => void;
  onAbstain?: () => void;
  busy?: boolean;
  autoFocus?: boolean;
}

/**
 * The one row of buttons. Approve is the filled primary; reject and abstain
 * are quiet and sit on the right, at equal weight to each other so that
 * "Can't tell" is as easy to reach as "no" (heuristic 5).
 */
export function DecisionBar({
  approveLabel,
  rejectLabel = "Reject",
  abstainLabel,
  onApprove,
  onReject,
  onAbstain,
  busy,
  autoFocus,
}: DecisionBarProps) {
  const primary = useRef<HTMLButtonElement>(null);
  useEffect(() => {
    if (autoFocus) primary.current?.focus();
  }, [autoFocus]);

  return (
    <div
      className="flex flex-wrap items-center gap-2 border-t border-border px-3 py-2"
      aria-busy={busy || undefined}
    >
      <button
        ref={primary}
        type="button"
        onClick={onApprove}
        disabled={busy}
        className={btnPrimary}
      >
        {busy ? <Loader /> : <Check className="h-3 w-3" aria-hidden="true" />}
        {approveLabel}
      </button>
      {busy && (
        <span className="sr-only" role="status">
          Working
        </span>
      )}
      <div className="ml-auto flex items-center gap-1">
        {abstainLabel && onAbstain && (
          <button
            type="button"
            onClick={onAbstain}
            disabled={busy}
            className={btnQuiet}
          >
            <HelpCircle className="h-3 w-3" aria-hidden="true" />
            {abstainLabel}
          </button>
        )}
        <button
          type="button"
          onClick={onReject}
          disabled={busy}
          className={btnQuiet}
        >
          <X className="h-3 w-3" aria-hidden="true" />
          {rejectLabel}
        </button>
      </div>
    </div>
  );
}

export type Resolution = "approved" | "rejected" | "abstained" | "dismissed";

export const RESOLUTION_TONE: Record<Resolution, Tone> = {
  approved: "ok",
  rejected: "bad",
  abstained: "warn",
  dismissed: "muted",
};

export const RESOLUTION_WORD: Record<Resolution, string> = {
  approved: "approved",
  rejected: "rejected",
  abstained: "couldn't tell",
  dismissed: "dismissed",
};

/**
 * What a surface becomes once decided. One line, the same on every card:
 * icon, subject, the outcome in words, Undo, and a "details" disclosure that
 * reopens the evidence read-only so the decision stays checkable
 * (heuristics 3 and 6).
 */
export function ResolvedLine({
  resolution,
  subject,
  onUndo,
  details,
  detailsId,
  className,
}: {
  resolution: Resolution;
  subject: ReactNode;
  onUndo?: () => void;
  details?: ReactNode;
  detailsId: string;
  className?: string;
}) {
  const [open, setOpen] = useState(false);
  const tone = RESOLUTION_TONE[resolution];
  const Icon =
    resolution === "approved" ? Check : resolution === "rejected" ? X : resolution === "abstained" ? HelpCircle : X;

  return (
    <div
      role="status"
      aria-live="polite"
      className={cn(
        "my-1.5 rounded-xl border bg-card text-xs",
        resolution === "dismissed" ? "border-dashed border-border" : "border-border",
        className,
      )}
    >
      <div className="flex items-center gap-2 px-3 py-1.5">
        <Icon className={cn("h-3.5 w-3.5 shrink-0", TONE_TEXT[tone])} aria-hidden="true" />
        <span className="min-w-0 flex-1 truncate">
          <span className="font-medium text-foreground">{subject}</span>
          <span className="text-muted-foreground"> · {RESOLUTION_WORD[resolution]}</span>
        </span>
        {details && (
          <button
            type="button"
            onClick={() => setOpen((o) => !o)}
            aria-expanded={open}
            aria-controls={detailsId}
            className={btnLink}
          >
            details
          </button>
        )}
        {onUndo && (
          <button type="button" onClick={onUndo} className={cn(btnLink, "inline-flex items-center gap-1")}>
            <RotateCcw className="h-2.5 w-2.5" aria-hidden="true" />
            undo
          </button>
        )}
      </div>
      {details && open && (
        <div id={detailsId} className="border-t border-border opacity-80">
          {details}
        </div>
      )}
    </div>
  );
}
