// GENERATED by `pnpm hitl:sync` from @hitl-kit/ui (hitl-ai2/packages/ui). Do not edit; edit the package.
export interface RegistryItem {
  name: string;
  title: string;
  description: string;
  type: "registry:ui" | "registry:lib";
  registryDependencies?: string[];
}

export const REGISTRY_ITEMS: RegistryItem[] = [
  {
    "name": "hitl-utils",
    "title": "cn utility",
    "description": "Tailwind classname merge helper used by every HITL Kit primitive.",
    "type": "registry:lib"
  },
  {
    "name": "hitl-types",
    "title": "HITL UI types",
    "description": "The props every decision surface shares (busy, error, help, allowAbstain, allowUndo, autoFocus) and the interrupt card's local state. Event and action types come from @hitl-kit/core.",
    "type": "registry:lib"
  },
  {
    "name": "hitl-shared",
    "title": "Shared decision pieces",
    "description": "The card frame, decision bar, resolved line, inline error, help line and chip that every decision surface is built from. One vocabulary, one set of button styles.",
    "type": "registry:lib",
    "registryDependencies": [
      "hitl-utils"
    ]
  },
  {
    "name": "hitl-subagent-meta",
    "title": "Subagent status metadata",
    "description": "Shared icon, color and plain label for the six agent execution states (idle, running, completed, error, skipped, cancelled).",
    "type": "registry:lib"
  },
  {
    "name": "hitl-ai-levels",
    "title": "AI generation levels",
    "description": "The five-point AI-generation ordinal and its accent progression, shared by every scale variant so a level cannot mean one thing in the slider and another in the badge.",
    "type": "registry:lib"
  },
  {
    "name": "hitl-fixtures",
    "title": "Demo events",
    "description": "Valid core events for the decision surfaces, for demos and tests. Spread one onto its primitive or feed it to HitlEventRenderer.",
    "type": "registry:lib"
  },
  {
    "name": "hitl-card",
    "title": "Interrupt Card",
    "description": "In-thread approval boundary for agent actions. Three semantic variants (search, review, write). Idle, expanded, confirmed and dismissed, and every resolution can be undone.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-types",
      "hitl-shared"
    ]
  },
  {
    "name": "subagent-status-card",
    "title": "Subagent Status Card",
    "description": "Single-row agent status with icon, label, detail, and state in words. Use to wrap any in-progress agentic task.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-subagent-meta"
    ]
  },
  {
    "name": "mini-trace",
    "title": "MiniTrace",
    "description": "Collapsible step-by-step renderer for agent reasoning. Thought, action, result. Makes supporting facts visible per §3.3 of the paper.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-shared"
    ]
  },
  {
    "name": "ai-generation-scale",
    "title": "AI Generation Scale",
    "description": "Five-segment ordinal scale indicating AI involvement in a piece of work. Embodies the scaffolding and expertise-matching principle from Dhillon et al. (2024).",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-ai-levels",
      "hitl-shared"
    ]
  },
  {
    "name": "ai-generation-slider",
    "title": "AI Generation Slider",
    "description": "The compact drag form of the AI generation scale. One header row and one track, no wrapping at 320px. Pointer drag snaps to five stops; arrow keys step and Home/End jump. Full slider ARIA.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-ai-levels"
    ]
  },
  {
    "name": "ai-generation-meter",
    "title": "AI Generation Meter",
    "description": "At-a-glance, read-only provenance for a list row or a header. Five thin segments filled to the current level plus the level name, as a single role=img element with no focusable children.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-ai-levels"
    ]
  },
  {
    "name": "ai-generation-badge",
    "title": "AI Generation Badge",
    "description": "The densest form of the AI generation scale: one pill with a five-dot micro-indicator and the level name. Static by default; given onAction it grows stepper buttons with 24px hit areas.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-ai-levels",
      "hitl-shared"
    ]
  },
  {
    "name": "context-chips",
    "title": "Context Chips",
    "description": "Pill chips representing context attached to an agent run. Notes, files, URLs. Removable with overflow truncation.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-shared"
    ]
  },
  {
    "name": "qa-flow",
    "title": "QA Flow",
    "description": "Multi-question approval card. Single-choice, multi-select, and freeform text. Submits to a resolved line that keeps the answers visible and can be reopened.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-types",
      "hitl-shared"
    ]
  },
  {
    "name": "writing-agent",
    "title": "Writing Agent",
    "description": "Compound widget for a draft-in-progress document. Title, target section, word range, evidence notes, and six status states.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-subagent-meta",
      "hitl-shared"
    ]
  },
  {
    "name": "research-agent",
    "title": "Research Agent",
    "description": "Three-mode config surface for a long-running research task. Create, follow-up, read URL.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-shared"
    ]
  },
  {
    "name": "batch-queue",
    "title": "Batch Approval Queue",
    "description": "Sequential approve and reject flow across mixed agent items. Auto-advances, can step back one item, and resolves to a summary state.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-types",
      "hitl-shared"
    ]
  },
  {
    "name": "search-result-card",
    "title": "Search Result Card",
    "description": "Ranked search result card with rank badge, metadata, snippet, and relevance bar.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils"
    ]
  },
  {
    "name": "approve-reject-row",
    "title": "Approve / Reject Row",
    "description": "The canonical decision row. Approve, reject, or can't tell; pending, approved, rejected, abstained; undo back to pending.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-shared"
    ]
  },
  {
    "name": "shared-primitives",
    "title": "Shared Primitives",
    "description": "The atomic palette. Accent swatches, the four approval badges, and the decision row that sets them.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "approve-reject-row"
    ]
  },
  {
    "name": "diff-result",
    "title": "Diff Result",
    "description": "Before/after diff card for proposed text or code edits. Per-hunk red/green strips; apply, keep original, or can't tell; undo. The primitive for any in-place edit the human should approve before it lands.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-types",
      "hitl-shared"
    ]
  },
  {
    "name": "citation-result",
    "title": "Citation Result",
    "description": "Single source-backed citation card. Claim on top, source attribution below, optional supporting quote and confidence. Verify, reject, or can't tell; undo.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-types",
      "hitl-shared"
    ]
  },
  {
    "name": "editable-plan",
    "title": "Editable Plan",
    "description": "Multi-step plan the human can reorder, rename, add to, or delete from before the agent executes. Locked steps cannot be removed. Submit or cancel; undo.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-types",
      "hitl-shared"
    ]
  },
  {
    "name": "tool-call-preview",
    "title": "Tool Call Preview",
    "description": "Preview a tool call (name, args, optional rationale and signals) so the human can approve, reject, or say they can't tell before execution. External scopes are flagged. Pairs with the gates layer.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-types",
      "hitl-shared"
    ]
  },
  {
    "name": "evidence-pointer",
    "title": "Evidence Pointer",
    "description": "Where a claim is grounded, not merely that it is. One row per pointer with source, locator in human units, and excerpt; sources consulted but not drawn from are listed so silence never reads as safety. Grounded, not supported, or can't tell; undo.",
    "type": "registry:ui",
    "registryDependencies": [
      "hitl-utils",
      "hitl-types",
      "hitl-shared"
    ]
  }
];

export const REGISTRY_BASE_URL = "https://www.hitlkit.dev/r";
