// GENERATED by `pnpm hitl:sync` from hitl-ai2/packages/ui (@hitl-kit/ui). Do not edit; edit the package.
import type { AgentStatus, PlanStep } from "./events";

/**
 * What the human did, as the wire format that flows back to the agent.
 *
 * Every primitive reports through one `onAction(action)` callback and every
 * action is a discriminated object on `kind`. The vocabulary is deliberately
 * small and shared: a tool call, a diff, a citation and a binary row all say
 * `approve` / `reject` / `abstain` / `undo`, whatever label the button shows,
 * so a consumer switching on `action.kind` never has to learn a primitive's
 * private verbs. Labels are presentation; kinds are protocol.
 *
 * `abstain` exists because "I cannot tell" is not "no" (see ApprovalState).
 * `undo` exists because a decision surface without an exit is a trap: the
 * human must be able to reverse a click within the same surface, and the
 * consumer must be told so it can reverse the resume.
 */

/** The three-way answer every gated decision offers. */
export type DecisionKind = "approve" | "reject" | "abstain";

/** Shared across every binary decision surface. */
export type ApprovalAction =
  | { kind: "approve" }
  | { kind: "reject" }
  | { kind: "abstain" }
  | { kind: "undo" };

/** Offered by every surface that can show an error: try the last thing again. */
export type RetryAction = { kind: "retry" };

/** Interrupt Card: confirm carries the optional note the human typed. */
export type HitlCardAction =
  | { kind: "approve"; note?: string }
  | { kind: "dismiss" }
  | { kind: "undo" }
  | RetryAction;

/** Tool Call Preview. */
export type ToolCallAction = ApprovalAction | RetryAction;

/** Diff Result: `approve` applies the edit. */
export type DiffAction = ApprovalAction | RetryAction;

/** Citation Result: `approve` verifies the citation. */
export type CitationAction = ApprovalAction | RetryAction;

/** Approve / Reject Row. */
export type ApproveRejectAction = ApprovalAction;

/** Editable Plan: submit carries the steps as the human left them. */
export type EditablePlanAction =
  | { kind: "submit"; steps: PlanStep[] }
  | { kind: "cancel" }
  | { kind: "undo" }
  | RetryAction;

/** One answer per QA question, discriminated the same way the question is. */
export type QAAnswer =
  | { id: string; kind: "single"; value: string }
  | { id: string; kind: "multi"; value: string[] }
  | { id: string; kind: "text"; value: string };

/** QA Flow. */
export type QAFlowAction =
  | { kind: "submit"; answers: QAAnswer[] }
  | { kind: "reset" };

/** Batch Queue: one event per item decided, one when the queue resolves. */
export type BatchQueueAction =
  | { kind: "decide"; id: string; decision: "approve" | "reject" }
  | { kind: "undo"; id: string }
  | { kind: "complete"; decisions: Record<string, "approve" | "reject"> }
  | { kind: "reset" };

/** AI Generation Scale, Slider and Badge. */
export type ScaleAction = { kind: "change"; value: number };

/** Context Chips. */
export type ContextChipsAction = { kind: "remove"; id: string };

/** MiniTrace: a step opened or closed. */
export type TraceAction = { kind: "toggle"; index: number; expanded: boolean };

/** Research Agent. */
export type ResearchAgentAction = {
  kind: "mode";
  mode: "create" | "followup" | "readurl";
};

/** Writing Agent: `open` is the human asking to see the draft. */
export type WritingAgentAction =
  | { kind: "open" }
  | { kind: "status"; status: AgentStatus };

/** Evidence Pointer: open a source at its locator, or dispute the claim. */
export type EvidencePointerAction =
  | { kind: "open"; sourceId: string }
  | { kind: "approve" }
  | { kind: "reject" }
  | { kind: "abstain" }
  | { kind: "undo" }
  | RetryAction;

/** Every action any HITL Kit primitive can report. */
export type HitlAction =
  | HitlCardAction
  | ApprovalAction
  | EditablePlanAction
  | QAFlowAction
  | BatchQueueAction
  | ScaleAction
  | ContextChipsAction
  | TraceAction
  | ResearchAgentAction
  | WritingAgentAction
  | EvidencePointerAction
  | RetryAction;

export type HitlActionKind = HitlAction["kind"];

/** Every action kind, for exhaustive switches and documentation. */
export const HITL_ACTION_KINDS = [
  "approve",
  "reject",
  "abstain",
  "undo",
  "dismiss",
  "submit",
  "cancel",
  "reset",
  "decide",
  "complete",
  "change",
  "remove",
  "toggle",
  "mode",
  "open",
  "status",
  "retry",
] as const satisfies readonly HitlActionKind[];

/** True when the action authorizes the gated thing to proceed. */
export function isApproval(action: HitlAction): boolean {
  return action.kind === "approve";
}
