// GENERATED by `pnpm hitl:sync` from hitl-ai2/packages/ui (@hitl-kit/ui). Do not edit; edit the package.
import { z } from "zod";

/**
 * Shared enums and building blocks reused across primitive events.
 */

/**
 * URL string that is guaranteed to be HTTP(S). Plain `z.string().url()`
 * accepts `javascript:` and `data:` URIs (because Node's URL constructor
 * parses them) — a malicious agent emitting one would let
 * `<a href={url}>` execute script when clicked. This refinement rejects
 * anything other than `http://` or `https://`.
 */
export const SafeUrlSchema = z
  .string()
  .url()
  .refine((u) => /^https?:\/\//i.test(u), {
    message: "url must use http(s) scheme",
  });

/**
 * Conservative caps for user-controlled strings. The schemas use these to
 * limit DoS surface: a 50MB title would slow the renderer and blow up
 * JSON.stringify in the MCP server. Tune up if a legitimate use case
 * requires longer.
 */
const TITLE_MAX = 200;
const SUBTITLE_MAX = 500;
const LABEL_MAX = 200;
const BODY_MAX = 5000;
const SCOPE_MAX = 128;
const TOOL_NAME_MAX = 200;

export const AgentStatusSchema = z.enum([
  "idle",
  "running",
  "completed",
  "error",
  "skipped",
  "cancelled",
]);
export type AgentStatus = z.infer<typeof AgentStatusSchema>;

/**
 * The outcome of a human decision.
 *
 * `abstained` is deliberately distinct from `rejected`. "I cannot determine
 * this" is not "no" — it is a reviewer declining to convert an unresolved
 * question into an authorization, and it is the honest answer whenever the
 * evidence does not support either call. Collapsing it into `rejected` throws
 * away the one signal that says the standard itself was unclear, and makes a
 * queue of ambiguous cases look like a queue of denials.
 *
 * Consumers that exhaustively switch on this union will need a branch for it;
 * that is intentional, and the reason this is a minor rather than a patch.
 */
export const ApprovalStateSchema = z.enum([
  "pending",
  "approved",
  "rejected",
  "abstained",
]);
export type ApprovalState = z.infer<typeof ApprovalStateSchema>;

/**
 * States that authorize the gated action to proceed.
 *
 * Exported so callers never hand-roll `state === "approved"` and silently
 * disagree about whether an abstention permits action. It does not.
 */
export const AUTHORIZING_STATES: readonly ApprovalState[] = ["approved"];

/** True only when the human's decision permits the gated action. */
export function isAuthorized(state: ApprovalState): boolean {
  return AUTHORIZING_STATES.includes(state);
}

/* ─── 01. Interrupt Card ────────────────────────────────────────────────── */

export const HitlCardEventSchema = z.object({
  kind: z.literal("hitl.card"),
  id: z.string().max(LABEL_MAX).optional(),
  variant: z.enum(["search", "review", "write"]),
  title: z.string().max(TITLE_MAX),
  subtitle: z.string().max(SUBTITLE_MAX),
  steps: z
    .array(
      z.object({
        label: z.string().max(LABEL_MAX),
        done: z.boolean(),
      }),
    )
    .max(50),
  runLabel: z.string().max(LABEL_MAX),
  editPlaceholder: z.string().max(LABEL_MAX).optional(),
});
export type HitlCardEvent = z.infer<typeof HitlCardEventSchema>;

/* ─── 02. Subagent Status ───────────────────────────────────────────────── */

export const SubagentStatusEventSchema = z.object({
  kind: z.literal("subagent.status"),
  id: z.string().max(LABEL_MAX).optional(),
  status: AgentStatusSchema,
  label: z.string().max(LABEL_MAX),
  detail: z.string().max(SUBTITLE_MAX).optional(),
});
export type SubagentStatusEvent = z.infer<typeof SubagentStatusEventSchema>;

/* ─── 03. MiniTrace ─────────────────────────────────────────────────────── */

export const TraceStepSchema = z.object({
  type: z.enum(["thought", "action", "result"]),
  label: z.string().max(LABEL_MAX),
  detail: z.string().max(BODY_MAX).optional(),
});
export type TraceStep = z.infer<typeof TraceStepSchema>;

export const MiniTraceEventSchema = z.object({
  kind: z.literal("trace.mini"),
  id: z.string().max(LABEL_MAX).optional(),
  steps: z.array(TraceStepSchema).max(100),
});
export type MiniTraceEvent = z.infer<typeof MiniTraceEventSchema>;

/* ─── 04. AI Generation Scale ───────────────────────────────────────────── */

export const AiGenerationScaleEventSchema = z.object({
  kind: z.literal("scale.ai_generation"),
  id: z.string().max(LABEL_MAX).optional(),
  value: z.number().int().min(0).max(4),
  labels: z.array(z.string().max(LABEL_MAX)).length(5).optional(),
});
export type AiGenerationScaleEvent = z.infer<
  typeof AiGenerationScaleEventSchema
>;

/* ─── 05. Context Chips ─────────────────────────────────────────────────── */

export const ContextChipItemSchema = z.object({
  id: z.string().max(LABEL_MAX),
  label: z.string().max(LABEL_MAX),
  color: z.string().max(LABEL_MAX),
});
export type ContextChipItem = z.infer<typeof ContextChipItemSchema>;

export const ContextChipsEventSchema = z.object({
  kind: z.literal("chips.context"),
  items: z.array(ContextChipItemSchema).max(200),
});
export type ContextChipsEvent = z.infer<typeof ContextChipsEventSchema>;

/* ─── 06. QA Flow ───────────────────────────────────────────────────────── */

export const QAQuestionSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("single"),
    id: z.string().max(LABEL_MAX),
    prompt: z.string().max(BODY_MAX),
    options: z.array(z.string().max(LABEL_MAX)).max(50),
  }),
  z.object({
    kind: z.literal("multi"),
    id: z.string().max(LABEL_MAX),
    prompt: z.string().max(BODY_MAX),
    options: z.array(z.string().max(LABEL_MAX)).max(50),
  }),
  z.object({
    kind: z.literal("text"),
    id: z.string().max(LABEL_MAX),
    prompt: z.string().max(BODY_MAX),
    placeholder: z.string().max(LABEL_MAX).optional(),
  }),
]);
export type QAQuestion = z.infer<typeof QAQuestionSchema>;

export const QAFlowEventSchema = z.object({
  kind: z.literal("qa.flow"),
  id: z.string().max(LABEL_MAX).optional(),
  questions: z.array(QAQuestionSchema).max(50),
  submitLabel: z.string().max(LABEL_MAX).optional(),
});
export type QAFlowEvent = z.infer<typeof QAFlowEventSchema>;

/* ─── 07. Writing Agent ─────────────────────────────────────────────────── */

export const WritingAgentEventSchema = z.object({
  kind: z.literal("agent.writing"),
  id: z.string().max(LABEL_MAX).optional(),
  status: AgentStatusSchema,
  title: z.string().max(TITLE_MAX),
  target: z.string().max(LABEL_MAX),
  wordRange: z.string().max(LABEL_MAX),
  evidence: z.array(z.string().max(BODY_MAX)).max(100),
});
export type WritingAgentEvent = z.infer<typeof WritingAgentEventSchema>;

/* ─── 08. Research Agent ────────────────────────────────────────────────── */

export const ResearchAgentEventSchema = z.object({
  kind: z.literal("agent.research"),
  id: z.string().max(LABEL_MAX).optional(),
  mode: z.enum(["create", "followup", "readurl"]),
  config: z
    .record(z.string().max(LABEL_MAX), z.string().max(BODY_MAX))
    .refine((c) => Object.keys(c).length <= 50, {
      message: "config has more than 50 keys",
    }),
});
export type ResearchAgentEvent = z.infer<typeof ResearchAgentEventSchema>;

/* ─── 09. Batch Queue ───────────────────────────────────────────────────── */

export const BatchQueueItemSchema = z.object({
  id: z.string().max(LABEL_MAX),
  label: z.string().max(BODY_MAX),
  kind: z.string().max(LABEL_MAX), // semantic kind ("search" | "write" | "research" | ...), consumer maps to icon
});
export type BatchQueueItem = z.infer<typeof BatchQueueItemSchema>;

export const BatchQueueEventSchema = z.object({
  kind: z.literal("batch.queue"),
  id: z.string().max(LABEL_MAX).optional(),
  items: z.array(BatchQueueItemSchema).max(500),
});
export type BatchQueueEvent = z.infer<typeof BatchQueueEventSchema>;

/* ─── 10. Search Result Card ────────────────────────────────────────────── */

export const SearchResultEventSchema = z.object({
  kind: z.literal("result.search"),
  id: z.string().max(LABEL_MAX).optional(),
  rank: z.number().int(),
  title: z.string().max(TITLE_MAX),
  authors: z.string().max(SUBTITLE_MAX),
  venue: z.string().max(LABEL_MAX),
  year: z.union([z.number(), z.string().max(LABEL_MAX)]),
  snippet: z.string().max(BODY_MAX),
  relevance: z.number().min(0).max(1),
  cites: z.number().optional(),
});
export type SearchResultEvent = z.infer<typeof SearchResultEventSchema>;

/* ─── 11. Approve / Reject ──────────────────────────────────────────────── */

export const ApproveRejectEventSchema = z.object({
  kind: z.literal("approval.binary"),
  id: z.string().max(LABEL_MAX).optional(),
  label: z.string().max(LABEL_MAX),
  meta: z.string().max(SUBTITLE_MAX).optional(),
  accent: z.string().max(LABEL_MAX).optional(),
  state: ApprovalStateSchema,
});
export type ApproveRejectEvent = z.infer<typeof ApproveRejectEventSchema>;

/* ─── 12. Diff Result ───────────────────────────────────────────────────── */

export const DiffHunkSchema = z.object({
  before: z.string().max(BODY_MAX * 4), // 20KB cap for diff content per side
  after: z.string().max(BODY_MAX * 4),
  startLine: z.number().int().optional(),
});
export type DiffHunk = z.infer<typeof DiffHunkSchema>;

export const DiffResultEventSchema = z.object({
  kind: z.literal("result.diff"),
  id: z.string().max(LABEL_MAX).optional(),
  title: z.string().max(TITLE_MAX),
  subtitle: z.string().max(SUBTITLE_MAX).optional(),
  language: z.string().max(LABEL_MAX).optional(),
  hunks: z.array(DiffHunkSchema).min(1).max(100),
  acceptLabel: z.string().max(LABEL_MAX).optional(),
  rejectLabel: z.string().max(LABEL_MAX).optional(),
});
export type DiffResultEvent = z.infer<typeof DiffResultEventSchema>;

/* ─── 13. Citation Result ───────────────────────────────────────────────── */

export const CitationSourceSchema = z.object({
  title: z.string().max(TITLE_MAX),
  authors: z.string().max(SUBTITLE_MAX),
  year: z.union([z.number(), z.string().max(LABEL_MAX)]),
  venue: z.string().max(LABEL_MAX).optional(),
  url: SafeUrlSchema.optional(),
  quote: z.string().max(BODY_MAX).optional(),
  pages: z.string().max(LABEL_MAX).optional(),
});
export type CitationSource = z.infer<typeof CitationSourceSchema>;

export const CitationResultEventSchema = z.object({
  kind: z.literal("result.citation"),
  id: z.string().max(LABEL_MAX).optional(),
  claim: z.string().max(BODY_MAX),
  source: CitationSourceSchema,
  confidence: z.number().min(0).max(1).optional(),
});
export type CitationResultEvent = z.infer<typeof CitationResultEventSchema>;

/* ─── 14. Editable Plan ─────────────────────────────────────────────────── */

export const PlanStepSchema = z.object({
  id: z.string().max(LABEL_MAX),
  label: z.string().max(LABEL_MAX),
  detail: z.string().max(BODY_MAX).optional(),
  locked: z.boolean().optional(),
});
export type PlanStep = z.infer<typeof PlanStepSchema>;

export const EditablePlanEventSchema = z.object({
  kind: z.literal("plan.editable"),
  id: z.string().max(LABEL_MAX).optional(),
  title: z.string().max(TITLE_MAX),
  subtitle: z.string().max(SUBTITLE_MAX).optional(),
  steps: z.array(PlanStepSchema).min(1).max(100),
  submitLabel: z.string().max(LABEL_MAX).optional(),
});
export type EditablePlanEvent = z.infer<typeof EditablePlanEventSchema>;

/* ─── 15. Tool Call Preview ─────────────────────────────────────────────── */

export const ToolCallSignalsSchema = z.object({
  confidence: z.number().min(0).max(1).optional(),
  costUsd: z.number().min(0).optional(),
  scope: z.array(z.string().max(SCOPE_MAX)).max(64).optional(),
});
export type ToolCallSignals = z.infer<typeof ToolCallSignalsSchema>;

const MAX_ARGS_DEPTH = 6;
const MAX_ARGS_KEYS = 64;
const MAX_ARGS_SERIALIZED = 64 * 1024; // 64 KB

/**
 * Defense against deeply-nested or oversized tool-call args. JSON.stringify
 * is O(n²) on deep structures and the MCP server stringifies the parsed
 * event before returning. A 100-level nested object can hang the server.
 * We cap depth, top-level key count, and total serialized size.
 */
function isToolCallArgsSafe(value: unknown): boolean {
  if (typeof value !== "object" || value === null) return false;
  if (Object.keys(value).length > MAX_ARGS_KEYS) return false;

  let serialized: string;
  try {
    serialized = JSON.stringify(value);
  } catch {
    return false; // circular ref or non-serializable
  }
  if (serialized.length > MAX_ARGS_SERIALIZED) return false;

  const seen = new WeakSet<object>();
  const check = (v: unknown, depth: number): boolean => {
    if (depth > MAX_ARGS_DEPTH) return false;
    if (v === null || typeof v !== "object") return true;
    if (seen.has(v as object)) return false; // circular
    seen.add(v as object);
    if (Array.isArray(v)) {
      for (const item of v) if (!check(item, depth + 1)) return false;
      return true;
    }
    for (const key of Object.keys(v)) {
      // Block prototype-pollution attempts at the schema layer too,
      // belt-and-braces with Zod's record key validation.
      if (key === "__proto__" || key === "constructor" || key === "prototype")
        return false;
      if (!check((v as Record<string, unknown>)[key], depth + 1)) return false;
    }
    return true;
  };
  return check(value, 0);
}

export const ToolCallPreviewEventSchema = z.object({
  kind: z.literal("tool.call"),
  id: z.string().max(LABEL_MAX).optional(),
  toolName: z.string().max(TOOL_NAME_MAX),
  rationale: z.string().max(BODY_MAX).optional(),
  args: z
    .record(z.string().max(LABEL_MAX), z.unknown())
    .refine(isToolCallArgsSafe, {
      message: `args must be <=${MAX_ARGS_KEYS} keys, <=${MAX_ARGS_DEPTH} levels deep, <=${MAX_ARGS_SERIALIZED} bytes, no prototype keys, no cycles`,
    }),
  signals: ToolCallSignalsSchema.optional(),
  approveLabel: z.string().max(LABEL_MAX).optional(),
  rejectLabel: z.string().max(LABEL_MAX).optional(),
});
export type ToolCallPreviewEvent = z.infer<typeof ToolCallPreviewEventSchema>;

/* ─── The discriminated union ───────────────────────────────────────────── */


/* ─── 16. Evidence Pointer ──────────────────────────────────────────────── */

/**
 * WHERE a claim is grounded, not merely THAT it is.
 *
 * A gate is only affordable when the checkable half of the standard has
 * already been checked. If the evidence is "this 40-page document", the
 * reviewer can only trust the agent or re-derive the answer themselves, and
 * both are failures of the gate: the first is a rubber stamp, the second
 * means the automation saved nothing. A pointer has to LOCATE the disputed
 * thing.
 *
 * Locators are a discriminated union rather than a loose {start, end} because
 * the units differ per modality and silently mixing them is how a highlight
 * lands on the wrong sentence. Ranges are half-open [start, end), matching
 * tag-kit's scope convention so the two families agree.
 */
export const EvidenceLocatorSchema = z.discriminatedUnion("type", [
  /** Character offsets into a named text source. */
  z.object({
    type: z.literal("span"),
    start: z.number().int().nonnegative(),
    end: z.number().int().nonnegative(),
  }),
  /** Normalised 0–1 box on a page or image, so it survives rescaling. */
  z.object({
    type: z.literal("bbox"),
    x: z.number().min(0).max(1),
    y: z.number().min(0).max(1),
    width: z.number().min(0).max(1),
    height: z.number().min(0).max(1),
    page: z.number().int().positive().optional(),
  }),
  /** Seconds into an audio or video asset. */
  z.object({
    type: z.literal("segment"),
    startSec: z.number().nonnegative(),
    endSec: z.number().nonnegative(),
  }),
  /** A whole named source, when nothing narrower is honest. */
  z.object({ type: z.literal("whole") }),
]);
export type EvidenceLocator = z.infer<typeof EvidenceLocatorSchema>;

export const EvidenceItemSchema = z.object({
  /** Stable id for the source this points into (document, asset, message). */
  sourceId: z.string().max(LABEL_MAX),
  /** Human-readable source name, shown when the pointer is rendered. */
  sourceLabel: z.string().max(TITLE_MAX),
  locator: EvidenceLocatorSchema,
  /** The quoted or described excerpt the locator resolves to. */
  excerpt: z.string().max(BODY_MAX).optional(),
  url: SafeUrlSchema.optional(),
});
export type EvidenceItem = z.infer<typeof EvidenceItemSchema>;

export const EvidencePointerEventSchema = z.object({
  kind: z.literal("evidence.pointer"),
  id: z.string().max(LABEL_MAX).optional(),
  /** The claim these pointers support or dispute. */
  claim: z.string().max(BODY_MAX),
  items: z.array(EvidenceItemSchema).max(50),
  /**
   * Sources the agent consulted but drew nothing from. Recording this is the
   * difference between "no evidence against" and "not looked for" — absence
   * has to be visible or the reviewer reads silence as safety.
   */
  notAssessed: z.array(z.string().max(TITLE_MAX)).max(50).default([]),
});
export type EvidencePointerEvent = z.infer<typeof EvidencePointerEventSchema>;

/**
 * Every HITL event an agent can emit. Use this schema to validate
 * streaming tool-call output from a framework adapter before handing
 * it to `<HitlEventRenderer />` for display.
 */
export const HitlEventSchema = z.discriminatedUnion("kind", [
  HitlCardEventSchema,
  SubagentStatusEventSchema,
  MiniTraceEventSchema,
  AiGenerationScaleEventSchema,
  ContextChipsEventSchema,
  QAFlowEventSchema,
  WritingAgentEventSchema,
  ResearchAgentEventSchema,
  BatchQueueEventSchema,
  SearchResultEventSchema,
  ApproveRejectEventSchema,
  DiffResultEventSchema,
  CitationResultEventSchema,
  EditablePlanEventSchema,
  ToolCallPreviewEventSchema,
  EvidencePointerEventSchema,
]);

export type HitlEvent = z.infer<typeof HitlEventSchema>;

/**
 * Literal string union of every supported event kind. Handy for
 * typing registry objects and exhaustive switch statements.
 */
export type HitlEventKind = HitlEvent["kind"];

export const HITL_EVENT_KINDS = [
  "hitl.card",
  "subagent.status",
  "trace.mini",
  "scale.ai_generation",
  "chips.context",
  "qa.flow",
  "agent.writing",
  "agent.research",
  "batch.queue",
  "result.search",
  "approval.binary",
  "result.diff",
  "result.citation",
  "plan.editable",
  "tool.call",
  "evidence.pointer",
] as const satisfies readonly HitlEventKind[];
