// GENERATED by `pnpm hitl:sync` from hitl-ai2/packages/ui (@hitl-kit/ui). Do not edit; edit the package.
/**
 * The five-point AI-generation ordinal, shared by every scale variant.
 *
 * One array of level names, one plain-language meaning per level, and one
 * colour progression. `AiGenerationScale`, `AiGenerationSlider`,
 * `AiGenerationMeter` and `AiGenerationBadge` all read from here, so a level
 * can never mean one thing in the slider and another in the badge.
 *
 * The visual idea is a continuum, not five dots: every density shows a track
 * filled to the current level, and the fill reveals the spectrum from
 * emerald (human) to rose (AI). Colour is the cue; the words carry the meaning.
 * Every label sits on `foreground` / `muted-foreground`, never on colour.
 */

export const AI_GENERATION_LEVELS = [
  "Human",
  "Mostly human",
  "Collaborative",
  "Mostly AI",
  "AI",
] as const;

export type AiGenerationLevelName = (typeof AI_GENERATION_LEVELS)[number];

/** What each level means, in one plain sentence. Shown under the readout. */
export const AI_GENERATION_MEANINGS = [
  "Written by a person. AI was not involved.",
  "A person wrote it; AI suggested edits.",
  "Written together, turn by turn.",
  "AI drafted it; a person edited and approved.",
  "Generated by AI and published as is.",
] as const;

/** Highest valid index. The scale is 0-based: 0 = Human, 4 = AI. */
export const AI_GENERATION_MAX = AI_GENERATION_LEVELS.length - 1;

/**
 * emerald → blue → amber → violet → rose, one per level.
 * Written as literal utility strings so Tailwind's source scan picks them up.
 */
export const AI_GENERATION_ACCENTS = [
  "bg-[color:var(--accent-emerald)]",
  "bg-[color:var(--accent-blue)]",
  "bg-[color:var(--accent-amber)]",
  "bg-[color:var(--accent-violet)]",
  "bg-[color:var(--accent-rose)]",
] as const;

/** Tinted pill per level: a soft fill and a matching edge, text stays on foreground. */
export const AI_GENERATION_TINTS = [
  "bg-[color:var(--accent-emerald)]/15 border-[color:var(--accent-emerald)]/40",
  "bg-[color:var(--accent-blue)]/15 border-[color:var(--accent-blue)]/40",
  "bg-[color:var(--accent-amber)]/15 border-[color:var(--accent-amber)]/40",
  "bg-[color:var(--accent-violet)]/15 border-[color:var(--accent-violet)]/40",
  "bg-[color:var(--accent-rose)]/15 border-[color:var(--accent-rose)]/40",
] as const;

/** The whole continuum as one gradient; the fill of every track reveals it. */
export const AI_GENERATION_SPECTRUM =
  "linear-gradient(90deg, var(--accent-emerald), var(--accent-blue), var(--accent-amber), var(--accent-violet), var(--accent-rose))";

/** Keep any incoming value inside 0…4 and integral. */
export function clampAiLevel(value: number): number {
  if (!Number.isFinite(value)) return 0;
  return Math.min(AI_GENERATION_MAX, Math.max(0, Math.round(value)));
}

/** The display name for a level, honouring a caller-supplied label override. */
export function aiLevelName(
  value: number,
  labels: readonly string[] = AI_GENERATION_LEVELS,
): string {
  return labels[clampAiLevel(value)] ?? AI_GENERATION_LEVELS[clampAiLevel(value)];
}

/** The plain-language meaning of a level. */
export function aiLevelMeaning(value: number): string {
  return AI_GENERATION_MEANINGS[clampAiLevel(value)];
}

/** The accent utility class for a level. */
export function aiLevelAccent(value: number): string {
  return AI_GENERATION_ACCENTS[clampAiLevel(value)];
}

/** The tinted-pill utility classes for a level. */
export function aiLevelTint(value: number): string {
  return AI_GENERATION_TINTS[clampAiLevel(value)];
}

/**
 * How much of a track to fill for a level, as a percentage. Level 0 fills a
 * fifth rather than nothing, so "Human" reads as a position, not as empty.
 */
export function aiLevelFill(value: number): number {
  return ((clampAiLevel(value) + 1) / AI_GENERATION_LEVELS.length) * 100;
}

/**
 * Screen-reader text for a level: "Collaborative, 3 of 5".
 * Position is 1-based because that is how a human counts the marks they see.
 */
export function aiLevelDescription(
  value: number,
  labels: readonly string[] = AI_GENERATION_LEVELS,
): string {
  const i = clampAiLevel(value);
  return `${aiLevelName(i, labels)}, ${i + 1} of ${AI_GENERATION_LEVELS.length}`;
}
