"use client";
// GENERATED by `pnpm hitl:sync` from hitl-ai2/packages/ui (@hitl-kit/ui). Do not edit; edit the package.

import { useRef, type KeyboardEvent, type RefObject } from "react";
import type { AiGenerationScaleEvent, ScaleAction } from "@/components/hitl/core";
import { cn } from "@/lib/utils";
import {
  AI_GENERATION_ACCENTS,
  AI_GENERATION_LEVELS,
  AI_GENERATION_MAX,
  aiLevelName,
  clampAiLevel,
} from "@/components/hitl/ai-generation-levels";

/**
 * Thumb is 18px with a 2px separation ring, so the run of stop positions is
 * inset by 11px at each end. That keeps the thumb inside the box at level 0
 * and level 4 instead of bleeding past it.
 */
const RAIL_INSET = 11;

export interface AiGenerationSliderProps
  extends Partial<Omit<AiGenerationScaleEvent, "value" | "labels">>,
    Pick<AiGenerationScaleEvent, "value"> {
  labels?: readonly string[];
  /** Omit for a read-only readout. */
  onAction?: (action: ScaleAction) => void;
  /** Optional right-hand micro-copy in the header row. Mono, muted. */
  hint?: string;
  ariaLabel?: string;
  className?: string;
}

/**
 * The compact drag scale: one header row and one track, about 58px tall,
 * and it holds together at 320px. Pointer drag snaps to the five stops;
 * arrows step, Home/End jump.
 */
export function AiGenerationSlider({
  value,
  onAction,
  labels = AI_GENERATION_LEVELS,
  hint,
  ariaLabel = "AI generation level",
  className,
}: AiGenerationSliderProps) {
  const interactive = typeof onAction === "function";
  const v = clampAiLevel(value);
  const name = aiLevelName(v, labels);

  const railRef = useRef<HTMLSpanElement>(null);
  const dragging = useRef(false);

  const commit = (next: number) => {
    const clamped = clampAiLevel(next);
    if (clamped !== v) onAction?.({ kind: "change", value: clamped });
  };

  const fromClientX = (clientX: number) => {
    const rect = railRef.current?.getBoundingClientRect();
    if (!rect || rect.width <= 0) return v;
    return clampAiLevel(((clientX - rect.left) / rect.width) * AI_GENERATION_MAX);
  };

  const onKeyDown = (e: KeyboardEvent<HTMLDivElement>) => {
    if (!interactive) return;
    let next: number;
    switch (e.key) {
      case "ArrowLeft":
      case "ArrowDown":
        next = v - 1;
        break;
      case "ArrowRight":
      case "ArrowUp":
        next = v + 1;
        break;
      case "Home":
        next = 0;
        break;
      case "End":
        next = AI_GENERATION_MAX;
        break;
      default:
        return;
    }
    e.preventDefault();
    commit(next);
  };

  return (
    <div className={cn("w-full select-none", className)}>
      <div className="flex items-baseline justify-between gap-3">
        <span className="min-w-0 truncate text-[13px] font-medium leading-4 text-foreground">{name}</span>
        {hint ? (
          <span className="min-w-0 shrink truncate font-mono text-[11px] leading-4 text-muted-foreground">
            {hint}
          </span>
        ) : null}
      </div>

      <div
        role="slider"
        tabIndex={interactive ? 0 : -1}
        aria-label={ariaLabel}
        aria-valuemin={0}
        aria-valuemax={AI_GENERATION_MAX}
        aria-valuenow={v}
        aria-valuetext={name}
        aria-readonly={interactive ? undefined : true}
        onKeyDown={onKeyDown}
        onPointerDown={(e) => {
          if (!interactive) return;
          e.currentTarget.setPointerCapture(e.pointerId);
          e.currentTarget.focus();
          dragging.current = true;
          commit(fromClientX(e.clientX));
        }}
        onPointerMove={(e) => {
          if (!interactive || !dragging.current) return;
          commit(fromClientX(e.clientX));
        }}
        onPointerUp={(e) => {
          dragging.current = false;
          if (e.currentTarget.hasPointerCapture(e.pointerId)) {
            e.currentTarget.releasePointerCapture(e.pointerId);
          }
        }}
        onPointerCancel={() => {
          dragging.current = false;
        }}
        className={cn(
          "group relative mt-1 h-[18px] w-full outline-none",
          interactive ? "cursor-pointer touch-none" : "cursor-default",
        )}
      >
        <span aria-hidden className="absolute inset-x-0 top-1/2 h-1.5 -translate-y-1/2 rounded-full bg-muted" />

        <span
          ref={railRef as RefObject<HTMLSpanElement>}
          aria-hidden
          className="absolute inset-y-0"
          style={{ left: RAIL_INSET, right: RAIL_INSET }}
        >
          {AI_GENERATION_LEVELS.map((_, i) => (
            <span
              key={i}
              style={{ left: `${(i / AI_GENERATION_MAX) * 100}%` }}
              className={cn(
                "absolute top-1/2 h-1.5 w-1.5 -translate-x-1/2 -translate-y-1/2 rounded-full transition-colors duration-150 motion-reduce:transition-none",
                i <= v ? AI_GENERATION_ACCENTS[v] : "bg-muted-foreground/35",
              )}
            />
          ))}
          {/* No transition on `left`: the thumb must track the pointer exactly. */}
          <span
            style={{ left: `${(v / AI_GENERATION_MAX) * 100}%` }}
            className={cn(
              "absolute top-1/2 h-[18px] w-[18px] -translate-x-1/2 -translate-y-1/2 rounded-[6px] bg-foreground ring-2 ring-background",
              "group-focus-visible:outline-2 group-focus-visible:outline-offset-2 group-focus-visible:outline-ring",
            )}
          />
        </span>
      </div>

      <div
        aria-hidden
        className="mt-2 flex items-baseline justify-between gap-2 font-mono text-[11px] leading-none text-muted-foreground"
      >
        <span>{labels[0]}</span>
        <span>{labels[AI_GENERATION_MAX]}</span>
      </div>
    </div>
  );
}
