// GENERATED by `pnpm hitl:sync` from hitl-ai2/packages/ui (@hitl-kit/ui). Do not edit; edit the package.
import type { AiGenerationScaleEvent } from "@/components/hitl/core";
import { cn } from "@/lib/utils";
import {
  AI_GENERATION_LEVELS,
  AI_GENERATION_SPECTRUM,
  aiLevelDescription,
  aiLevelFill,
  aiLevelName,
  clampAiLevel,
} from "@/components/hitl/ai-generation-levels";

export interface AiGenerationMeterProps
  extends Partial<Omit<AiGenerationScaleEvent, "value" | "labels">>,
    Pick<AiGenerationScaleEvent, "value"> {
  labels?: readonly string[];
  /** Drop the level name and keep only the bar, for very tight cells. */
  compact?: boolean;
  /** Overrides the generated description, e.g. "Provenance: Collaborative, 3 of 5". */
  ariaLabel?: string;
  className?: string;
}

/**
 * At-a-glance provenance: one short track filled to the current level with
 * the spectrum, plus the level name. Deliberately read-only and a single
 * `role="img"`, so a table of fifty rows does not add fifty tab stops.
 * No "use client": no state, no handlers.
 */
export function AiGenerationMeter({
  value,
  labels = AI_GENERATION_LEVELS,
  compact = false,
  ariaLabel,
  className,
}: AiGenerationMeterProps) {
  const v = clampAiLevel(value);
  const fill = aiLevelFill(v);

  return (
    <span
      role="img"
      aria-label={ariaLabel ?? aiLevelDescription(v, labels)}
      className={cn("inline-flex h-5 max-w-full items-center gap-2 align-middle", className)}
    >
      <span className="relative h-1.5 w-12 shrink-0 overflow-hidden rounded-full bg-muted">
        <span
          className="absolute inset-y-0 left-0 rounded-full"
          style={{ width: `${fill}%`, background: AI_GENERATION_SPECTRUM, backgroundSize: `${10000 / fill}% 100%` }}
        />
      </span>
      {compact ? null : (
        <span className="truncate text-[11px] font-medium leading-none text-foreground">{aiLevelName(v, labels)}</span>
      )}
    </span>
  );
}
