// GENERATED by `pnpm hitl:sync` from hitl-ai2/packages/ui (@hitl-kit/ui). Do not edit; edit the package.
import type { AiGenerationScaleEvent } from "@/components/hitl/core";
import { cn } from "@/lib/utils";
import {
  AI_GENERATION_ACCENTS,
  AI_GENERATION_LEVELS,
  aiLevelDescription,
  aiLevelName,
  clampAiLevel,
} from "@/components/hitl/ai-generation-levels";

export interface AiGenerationMeterProps
  extends Partial<Omit<AiGenerationScaleEvent, "value" | "labels">>,
    Pick<AiGenerationScaleEvent, "value"> {
  labels?: readonly string[];
  /** Drop the level name and keep only the segments, for very tight cells. */
  compact?: boolean;
  /** Overrides the generated description, e.g. "Provenance: Collaborative, 3 of 5". */
  ariaLabel?: string;
  className?: string;
}

/**
 * At-a-glance provenance: five segments filled to the current level, plus the
 * level name. Deliberately read-only and a single `role="img"`, so a table of
 * fifty rows does not add fifty tab stops. No "use client": no state, no handlers.
 */
export function AiGenerationMeter({
  value,
  labels = AI_GENERATION_LEVELS,
  compact = false,
  ariaLabel,
  className,
}: AiGenerationMeterProps) {
  const v = clampAiLevel(value);
  const accent = AI_GENERATION_ACCENTS[v];

  return (
    <span
      role="img"
      aria-label={ariaLabel ?? aiLevelDescription(v, labels)}
      className={cn("inline-flex h-5 max-w-full items-center gap-2 align-middle", className)}
    >
      <span className="flex shrink-0 items-center gap-1">
        {AI_GENERATION_LEVELS.map((_, i) => (
          <span key={i} className={cn("h-[3px] w-4 rounded-sm", i <= v ? accent : "bg-muted")} />
        ))}
      </span>
      {compact ? null : (
        <span className="truncate font-mono text-[11px] leading-none text-foreground">
          {aiLevelName(v, labels)}
        </span>
      )}
    </span>
  );
}
