"use client";
// GENERATED by `pnpm hitl:sync` from @hitl-kit/ui (hitl-ai2/packages/ui). Do not edit; edit the package.

import { useId, useState } from "react";
import { Crosshair, ExternalLink, EyeOff } from "lucide-react";
import type {
  EvidenceItem,
  EvidenceLocator,
  EvidencePointerAction,
  EvidencePointerEvent,
} from "@/components/hitl/core";
import type { DecisionSurfaceProps } from "@/components/hitl/types";
import {
  Card,
  Chip,
  DecisionBar,
  HelpLine,
  InlineError,
  ResolvedLine,
  focusRing,
  motion,
  type Resolution,
} from "@/components/hitl/internal/ui";
import { cn } from "@/lib/utils";

export interface EvidencePointerProps
  extends Omit<EvidencePointerEvent, "notAssessed">,
    DecisionSurfaceProps {
  notAssessed?: string[];
  onAction?: (action: EvidencePointerAction) => void;
}

/** A locator in the units a person reads, never a raw object. */
export function describeLocator(l: EvidenceLocator): string {
  switch (l.type) {
    case "span":
      return `characters ${l.start}–${l.end}`;
    case "bbox":
      return `${l.page !== undefined ? `page ${l.page}, ` : ""}box at ${Math.round(l.x * 100)}%, ${Math.round(l.y * 100)}%`;
    case "segment":
      return `${fmtSec(l.startSec)}–${fmtSec(l.endSec)}`;
    case "whole":
      return "whole source";
  }
}

function fmtSec(s: number): string {
  const m = Math.floor(s / 60);
  const r = Math.floor(s % 60);
  return `${m}:${String(r).padStart(2, "0")}`;
}

function PointerRow({
  item,
  onOpen,
}: {
  item: EvidenceItem;
  onOpen?: () => void;
}) {
  const where = describeLocator(item.locator);
  return (
    <li className="px-3 py-2">
      <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
        <Crosshair className="h-3 w-3 shrink-0 text-[color:var(--accent-violet)]" aria-hidden="true" />
        <span className="font-medium text-foreground">{item.sourceLabel}</span>
        <Chip title="Where in the source this points">{where}</Chip>
        {(item.url || onOpen) && (
          <a
            href={item.url}
            target={item.url ? "_blank" : undefined}
            rel="noreferrer"
            onClick={onOpen}
            aria-label={`Open ${item.sourceLabel} at ${where}`}
            className={cn(
              "ml-auto inline-flex items-center gap-1 rounded text-[11px] text-muted-foreground hover:text-foreground",
              motion,
              focusRing,
            )}
          >
            open
            <ExternalLink className="h-3 w-3" aria-hidden="true" />
          </a>
        )}
      </div>
      {item.excerpt && (
        <blockquote className="mt-1 border-l-2 border-[color:var(--accent-violet)]/40 pl-2 italic leading-relaxed text-muted-foreground">
          {item.excerpt}
        </blockquote>
      )}
    </li>
  );
}

/**
 * Evidence Pointer. WHERE a claim is grounded, not merely that it is: one row
 * per pointer with the source, the locator in human units, and the excerpt.
 * Sources the agent consulted and drew nothing from are listed too, because
 * silence must not read as safety.
 */
export function EvidencePointer({
  id,
  claim,
  items,
  notAssessed = [],
  onAction,
  busy,
  error,
  help,
  allowAbstain = true,
  allowUndo = true,
  autoFocus,
  className,
}: EvidencePointerProps) {
  const [resolution, setResolution] = useState<Resolution | null>(null);
  const uid = useId();
  const baseId = `evidence-${id ?? uid}`;

  const body = (
    <>
      <p className="px-3 py-2.5 text-[13px] leading-relaxed text-foreground">{claim}</p>
      {items.length > 0 ? (
        <ul className="divide-y divide-border border-t border-border" aria-label="Evidence pointers">
          {items.map((item, i) => (
            <PointerRow
              key={`${item.sourceId}-${i}`}
              item={item}
              onOpen={onAction && (() => onAction({ kind: "open", sourceId: item.sourceId }))}
            />
          ))}
        </ul>
      ) : (
        <p className="border-t border-border px-3 py-2 text-[11px] text-[color:var(--accent-amber)]">
          No pointer given. The claim is unlocated.
        </p>
      )}
      {notAssessed.length > 0 && (
        <p className="flex items-start gap-1.5 border-t border-border px-3 py-2 text-[11px] leading-relaxed text-muted-foreground">
          <EyeOff className="mt-0.5 h-3 w-3 shrink-0" aria-hidden="true" />
          <span>
            <span className="text-foreground">Not assessed:</span> {notAssessed.join(", ")}
          </span>
        </p>
      )}
    </>
  );

  if (resolution) {
    return (
      <ResolvedLine
        resolution={resolution}
        subject={claim}
        onUndo={
          allowUndo
            ? () => {
                setResolution(null);
                onAction?.({ kind: "undo" });
              }
            : undefined
        }
        details={body}
        detailsId={`${baseId}-resolved`}
        className={className}
      />
    );
  }

  const decide = (r: Resolution, action: EvidencePointerAction) => {
    setResolution(r);
    onAction?.(action);
  };

  return (
    <Card label="Evidence for review" className={className}>
      <div className="flex items-center gap-2 border-b border-border px-3 py-2">
        <Crosshair className="h-3.5 w-3.5 shrink-0 text-[color:var(--accent-violet)]" aria-hidden="true" />
        <span className="text-[13px] font-medium text-foreground">Evidence</span>
        <Chip className="ml-auto" title="Pointers into sources, and sources not assessed">
          {items.length} located · {notAssessed.length} not assessed
        </Chip>
      </div>
      <HelpLine text={help} />
      {body}
      <InlineError message={error} onRetry={onAction && (() => onAction({ kind: "retry" }))} />
      <DecisionBar
        approveLabel="Grounded"
        rejectLabel="Not supported"
        abstainLabel={allowAbstain ? "Can't tell" : undefined}
        onApprove={() => decide("approved", { kind: "approve" })}
        onReject={() => decide("rejected", { kind: "reject" })}
        onAbstain={() => decide("abstained", { kind: "abstain" })}
        busy={busy}
        autoFocus={autoFocus}
      />
    </Card>
  );
}
