// GENERATED by `pnpm hitl:sync` from hitl-ai2/packages/ui (@hitl-kit/ui). Do not edit; edit the package.
import type {
  CitationResultEvent,
  DiffResultEvent,
  EvidencePointerEvent,
  HitlCardEvent,
  ToolCallPreviewEvent,
} from "@/components/hitl/core";

/**
 * Demo events for the decision surfaces. Each is a valid core event, so it
 * can be spread straight onto its primitive or fed to `HitlEventRenderer`.
 */

export const DEMO_HITL_CARDS: HitlCardEvent[] = [
  {
    kind: "hitl.card",
    id: "h1",
    variant: "search",
    title: "177 results found",
    subtitle: '"climate adaptation strategies"',
    steps: [
      { label: "Search complete", done: true },
      { label: "Refine query", done: false },
      { label: "Update panel", done: false },
    ],
    runLabel: "Run refined search",
    editPlaceholder: "Add query notes or constraints…",
  },
  {
    kind: "hitl.card",
    id: "h2",
    variant: "review",
    title: "Citation needs verification",
    subtitle: "Table 3 · IPCC 2023 p. 12",
    steps: [
      { label: "Flagged by agent", done: true },
      { label: "Add note", done: false },
      { label: "Resume writing", done: false },
    ],
    runLabel: "Confirm & continue",
    editPlaceholder: "Add verification note…",
  },
  {
    kind: "hitl.card",
    id: "h3",
    variant: "write",
    title: "Section 2 updated",
    subtitle: "2 new citations added",
    steps: [
      { label: "Citation 1 inserted", done: true },
      { label: "Citation 2 inserted", done: true },
      { label: "Confirm to lock", done: false },
    ],
    runLabel: "Lock & continue",
  },
];

export const DEMO_TOOL_CALL: ToolCallPreviewEvent = {
  kind: "tool.call",
  id: "demo-tool-call",
  toolName: "send_email",
  rationale:
    "Drafted reply to the client thread; confirming high-stakes outbound before sending.",
  args: {
    to: "client@example.com",
    subject: "Re: Q3 deliverable timeline",
    body: "Thanks for flagging the schedule risk, I've replanned around the milestone you raised and will send a revised plan by Friday.",
    cc: ["pm@internal.com"],
  },
  signals: {
    confidence: 0.86,
    costUsd: 0.0012,
    scope: ["write:email", "send:external"],
  },
  approveLabel: "Send email",
  rejectLabel: "Hold",
};

export const DEMO_DIFF: DiffResultEvent = {
  kind: "result.diff",
  id: "demo-diff",
  title: "Tighten introduction paragraph",
  subtitle: "Removes hedging, names the thesis directly",
  language: "markdown",
  hunks: [
    {
      startLine: 1,
      before:
        "It seems like the central question of this paper might be how AI systems should be evaluated when they are deployed in collaborative settings.",
      after:
        "This paper argues that AI systems must be evaluated against collaborative performance, not autonomous task completion.",
    },
  ],
  acceptLabel: "Apply edit",
  rejectLabel: "Keep original",
};

export const DEMO_CITATION: CitationResultEvent = {
  kind: "result.citation",
  id: "demo-citation",
  claim:
    "Roughly 95% of enterprise generative-AI pilots fail to reach production deployment.",
  source: {
    title: "The GenAI Divide: State of AI in Business 2025",
    authors: "Challapally et al.",
    year: 2025,
    venue: "MIT NANDA",
    url: "https://example.com/genai-divide",
    quote:
      "Across 312 enterprise rollouts surveyed in Q1-Q3 2025, only 5.4 percent reached sustained production usage; the remainder either stalled in pilot or were withdrawn within 90 days of go-live.",
    pages: "12-14",
  },
  confidence: 0.78,
};

export const DEMO_EVIDENCE: EvidencePointerEvent = {
  kind: "evidence.pointer",
  id: "demo-evidence",
  claim:
    "The comment addresses the recipient by name and repeats a threat made in an earlier post.",
  items: [
    {
      sourceId: "asset-8813",
      sourceLabel: "Comment #8813",
      locator: { type: "span", start: 42, end: 97 },
      excerpt: "…you know exactly where I'll be waiting for you, Dana.",
    },
    {
      sourceId: "asset-8801",
      sourceLabel: "Earlier post #8801",
      locator: { type: "span", start: 0, end: 61 },
      excerpt: "I'll be waiting outside after the meeting.",
      url: "https://example.com/posts/8801",
    },
  ],
  notAssessed: ["Direct messages between the accounts", "Reports from other users"],
};
