"use client";
// GENERATED by `pnpm hitl:sync` from hitl-ai2/packages/ui (@hitl-kit/ui). Do not edit; edit the package.

import type { SearchResultEvent } from "@/components/hitl/core";
import { cn } from "@/lib/utils";

export interface SearchResultCardProps
  extends Partial<Pick<SearchResultEvent, "kind" | "id" | "cites">>,
    Omit<SearchResultEvent, "kind" | "id" | "cites"> {
  className?: string;
}

/**
 * Search Result Card. Rank, title, authors, snippet, and a relevance bar.
 * The relevance is a signal for the human to weigh, not a verdict.
 */
export function SearchResultCard({
  rank,
  title,
  authors,
  venue,
  year,
  snippet,
  relevance,
  cites,
  className,
}: SearchResultCardProps) {
  const pct = Math.round(relevance * 100);
  return (
    <article className={cn("", className)} aria-label={`Result ${rank}: ${title}`}>
      <div className="mb-1 flex items-start gap-2">
        <div
          className="flex h-5 w-5 shrink-0 items-center justify-center rounded-md bg-gradient-to-br from-[color:var(--accent-violet)] to-[color:var(--accent-blue)] text-[11px] font-bold text-white"
          aria-hidden="true"
        >
          {rank}
        </div>
        <p className="text-xs font-medium leading-snug text-foreground">{title}</p>
      </div>
      <p className="mb-1 text-[11px] text-muted-foreground">
        {authors}
        <span className="sr-only">, </span>
        <span aria-hidden="true"> · </span>
        {venue}, {year}
        {cites !== undefined && (
          <>
            <span aria-hidden="true"> · </span>
            <span title={`Cited ${cites} times`}>{cites} citations</span>
          </>
        )}
      </p>
      <p className="mb-2 line-clamp-2 text-[11px] leading-relaxed text-muted-foreground">{snippet}</p>
      <div className="flex items-center gap-2">
        <div
          className="h-1 flex-1 overflow-hidden rounded-full bg-muted"
          role="meter"
          aria-label="Relevance"
          aria-valuemin={0}
          aria-valuemax={100}
          aria-valuenow={pct}
        >
          <div
            className="h-full rounded-full bg-[color:var(--accent-violet)] transition-[width] duration-300 ease-out motion-reduce:transition-none"
            style={{ width: `${pct}%` }}
          />
        </div>
        <span className="text-[11px] text-muted-foreground" title="Relevance, as the agent scored it">
          {pct}%
        </span>
      </div>
    </article>
  );
}

export const DEMO_SEARCH_RESULTS: SearchResultEvent[] = [
  {
    kind: "result.search",
    id: "s1",
    rank: 1,
    title: "Carbon Pricing Mechanisms and Emissions Outcomes",
    venue: "Nature Climate Change",
    year: 2023,
    authors: "Stavins, R., Stowe, R., Comstock, M.",
    snippet:
      "Empirical analysis of 40 carbon pricing schemes across 30 jurisdictions reveals that price levels above $50/tCO₂ are associated with meaningful emissions reductions in the power sector...",
    relevance: 0.97,
    cites: 412,
  },
  {
    kind: "result.search",
    id: "s2",
    rank: 2,
    title: "Just Transition Frameworks in Coal-Dependent Regions",
    venue: "arXiv",
    year: 2024,
    authors: "Newell, P., Mulvaney, D.",
    snippet:
      "A systematic review of 28 coal phase-out programmes finds that regions with co-designed transition plans achieved 34% higher re-employment rates within 24 months...",
    relevance: 0.91,
    cites: 87,
  },
  {
    kind: "result.search",
    id: "s3",
    rank: 3,
    title: "Net Zero Pledges: Verification and Accountability",
    venue: "Science",
    year: 2023,
    authors: "Höhne, N., Gidden, M., den Elzen, M.",
    snippet:
      "Of 196 national net zero pledges examined, only 31% include robust interim milestones and independent verification mechanisms aligned with 1.5°C pathways...",
    relevance: 0.88,
    cites: 301,
  },
  {
    kind: "result.search",
    id: "s4",
    rank: 4,
    title: "EU Emissions Trading System Post-Reform Price Dynamics",
    venue: "Energy Economics",
    year: 2024,
    authors: "Borghesi, S., Flori, A.",
    snippet:
      "The Market Stability Reserve mechanism introduced in 2019 has demonstrably reduced permit surplus, contributing to a tripling of EUA prices from 2018 to 2023...",
    relevance: 0.84,
    cites: 156,
  },
];
