"use client";
// GENERATED by `pnpm hitl:sync` from hitl-ai2/packages/ui (@hitl-kit/ui). Do not edit; edit the package.

import { useState } from "react";
import type { ApprovalState } from "@/components/hitl/core";
import { cn } from "@/lib/utils";
import { ApproveRejectRow } from "@/components/hitl/ApproveRejectRow";

/** Each accent has one job. Name the job, not just the hue. */
const ACCENTS = [
  { label: "Violet", role: "Search and evidence", color: "bg-[color:var(--accent-violet)]" },
  { label: "Amber", role: "Review, hold, can't tell", color: "bg-[color:var(--accent-amber)]" },
  { label: "Blue", role: "Writing and running", color: "bg-[color:var(--accent-blue)]" },
  { label: "Emerald", role: "Approved", color: "bg-[color:var(--accent-emerald)]" },
  { label: "Rose", role: "Rejected", color: "bg-[color:var(--accent-rose)]" },
];

const APPROVAL_STATES: ApprovalState[] = ["pending", "approved", "rejected", "abstained"];

const APPROVAL_BADGE: Record<ApprovalState, { word: string; className: string }> = {
  pending: { word: "Pending", className: "bg-[color:var(--accent-amber)]/10 text-[color:var(--accent-amber)]" },
  approved: { word: "Approved", className: "bg-[color:var(--accent-emerald)]/10 text-[color:var(--accent-emerald)]" },
  rejected: { word: "Rejected", className: "bg-[color:var(--accent-rose)]/10 text-[color:var(--accent-rose)]" },
  abstained: { word: "Couldn't tell", className: "bg-[color:var(--accent-amber)]/10 text-[color:var(--accent-amber)]" },
};

function Heading({ children, note }: { children: string; note?: string }) {
  return (
    <div className="mb-2.5 flex items-baseline justify-between gap-3">
      <p className="text-xs font-medium text-foreground">{children}</p>
      {note && <p className="text-[11px] text-muted-foreground">{note}</p>}
    </div>
  );
}

/** The palette the kit draws from: five accents with their jobs, the four approval badges, and the decision row that sets them. */
export function SharedPrimitives({ className }: { className?: string }) {
  const [approvals, setApprovals] = useState<Record<string, ApprovalState>>({
    a: "pending",
    b: "pending",
    c: "pending",
  });

  return (
    <div className={cn("space-y-6", className)}>
      <div>
        <Heading note="colour is punctuation, never a background for text">Accents</Heading>
        <ul className="m-0 grid list-none gap-2 p-0 sm:grid-cols-2">
          {ACCENTS.map((a) => (
            <li key={a.label} className="flex items-center gap-3 rounded-lg border border-border bg-background/40 px-3 py-2">
              <span className={cn("h-4 w-4 shrink-0 rounded-md", a.color)} aria-hidden="true" />
              <span className="min-w-0">
                <span className="block text-xs font-medium text-foreground">{a.label}</span>
                <span className="block truncate text-[11px] text-muted-foreground">{a.role}</span>
              </span>
            </li>
          ))}
        </ul>
      </div>

      <div>
        <Heading note="four states, because can't tell is not no">Approval badges</Heading>
        <div className="flex flex-wrap gap-2">
          {APPROVAL_STATES.map((s) => (
            <span key={s} className={cn("rounded-full px-2.5 py-1 text-[11px] font-medium", APPROVAL_BADGE[s].className)}>
              {APPROVAL_BADGE[s].word}
            </span>
          ))}
        </div>
      </div>

      <div>
        <Heading note="undo returns to pending">Decision rows</Heading>
        <div className="space-y-1.5">
          {(["a", "b", "c"] as const).map((k) => (
            <div key={k} className="rounded-lg border border-border bg-background/40 px-3 py-2">
              <ApproveRejectRow
                label={`Item ${k.toUpperCase()}`}
                state={approvals[k]}
                onAction={(a) =>
                  setApprovals((p) => ({
                    ...p,
                    [k]:
                      a.kind === "approve"
                        ? "approved"
                        : a.kind === "reject"
                          ? "rejected"
                          : a.kind === "abstain"
                            ? "abstained"
                            : "pending",
                  }))
                }
              />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
