// GENERATED by `pnpm hitl:sync` from @hitl-kit/ui (hitl-ai2/packages/ui). Do not edit; edit the package.
import type { ElementType } from "react";
import {
  Cpu,
  Loader2,
  Check,
  AlertOctagon,
  SkipForward,
  Ban,
} from "lucide-react";
import type { AgentStatus } from "@/components/hitl/core";

/** One icon, colour and plain label per agent status, shared by every card that shows one. */
export const STATUS_META: Record<
  AgentStatus,
  { icon: ElementType; color: string; label: string }
> = {
  idle: { icon: Cpu, color: "text-muted-foreground", label: "Idle" },
  running: { icon: Loader2, color: "text-[color:var(--accent-blue)]", label: "Running" },
  completed: { icon: Check, color: "text-[color:var(--accent-emerald)]", label: "Completed" },
  error: { icon: AlertOctagon, color: "text-[color:var(--accent-rose)]", label: "Error" },
  skipped: { icon: SkipForward, color: "text-[color:var(--accent-amber)]", label: "Skipped" },
  cancelled: { icon: Ban, color: "text-muted-foreground", label: "Cancelled" },
};
