"use client";
// GENERATED by `pnpm hitl:sync` from @hitl-kit/ui (hitl-ai2/packages/ui). Do not edit; edit the package.

import { useState, type ElementType } from "react";
import { Check, FileText, GraduationCap, PenLine, RotateCcw, Search, X } from "lucide-react";
import type { BatchQueueAction, BatchQueueEvent, BatchQueueItem } from "@/components/hitl/core";
import { cn } from "@/lib/utils";
import type { DecisionSurfaceProps } from "@/components/hitl/types";
import { HelpLine, InlineError, btnLink, focusRing, motion } from "@/components/hitl/internal/ui";

export type { BatchQueueItem };

type Decision = "approve" | "reject";

export interface BatchQueueProps
  extends Partial<Omit<BatchQueueEvent, "items">>,
    Pick<BatchQueueEvent, "items">,
    Omit<DecisionSurfaceProps, "allowAbstain"> {
  onAction?: (action: BatchQueueAction) => void;
  /** Icon per item `kind`. Unknown kinds fall back to a document icon. */
  icons?: Record<string, ElementType>;
}

const DEFAULT_ICONS: Record<string, ElementType> = {
  search: Search,
  write: PenLine,
  research: GraduationCap,
  read: FileText,
};

/**
 * Batch Queue. One decision per row, in order; the queue advances itself.
 * "Undo last" steps back one row, and the summary can be reset.
 */
export function BatchQueue({
  items,
  onAction,
  icons,
  busy,
  error,
  help,
  allowUndo = true,
  autoFocus,
  className,
}: BatchQueueProps) {
  const [decisions, setDecisions] = useState<Record<string, Decision | null>>(
    Object.fromEntries(items.map((i) => [i.id, null])),
  );
  const [current, setCurrent] = useState(0);
  const iconFor = (kind: string) => icons?.[kind] ?? DEFAULT_ICONS[kind] ?? FileText;

  const decide = (id: string, d: Decision) => {
    const next = { ...decisions, [id]: d };
    setDecisions(next);
    onAction?.({ kind: "decide", id, decision: d });
    setCurrent((c) => Math.min(c + 1, items.length));
    if (Object.values(next).every((x) => x !== null)) {
      onAction?.({
        kind: "complete",
        decisions: Object.fromEntries(Object.entries(next).map(([k, v]) => [k, v as Decision])),
      });
    }
  };

  const undoLast = () => {
    if (current === 0) return;
    const prev = items[current - 1];
    if (!prev) return;
    setDecisions((p) => ({ ...p, [prev.id]: null }));
    setCurrent(current - 1);
    onAction?.({ kind: "undo", id: prev.id });
  };

  const reset = () => {
    setDecisions(Object.fromEntries(items.map((i) => [i.id, null])));
    setCurrent(0);
    onAction?.({ kind: "reset" });
  };

  const allDone = items.length > 0 && Object.values(decisions).every((d) => d !== null);
  const approvedCount = Object.values(decisions).filter((d) => d === "approve").length;

  if (allDone) {
    return (
      <div className={cn("space-y-3 text-center", className)} role="status" aria-live="polite">
        <Check className="mx-auto h-8 w-8 text-[color:var(--accent-emerald)]" aria-hidden="true" />
        <div>
          <p className="text-[13px] font-semibold text-foreground">Batch complete</p>
          <p className="mt-0.5 text-xs text-muted-foreground">
            {approvedCount} approved · {items.length - approvedCount} rejected
          </p>
        </div>
        <div className="flex items-center justify-center gap-3">
          {allowUndo && (
            <button type="button" onClick={undoLast} className={cn(btnLink, "inline-flex items-center gap-1")}>
              <RotateCcw className="h-2.5 w-2.5" aria-hidden="true" />
              undo last
            </button>
          )}
          <button type="button" onClick={reset} className={btnLink}>
            reset
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className={cn("overflow-hidden rounded-lg border border-border", className)} aria-busy={busy || undefined}>
      <HelpLine text={help} />
      <ol className="m-0 list-none divide-y divide-border p-0" aria-label="Items awaiting decision">
        {items.map((item, i) => {
          const Icon = iconFor(item.kind);
          const d = decisions[item.id];
          const isActive = i === current;
          return (
            <li
              key={item.id}
              aria-current={isActive ? "step" : undefined}
              className={cn("flex items-center gap-3 px-3 py-2.5 text-xs", motion, isActive && "bg-muted/50")}
            >
              <Icon className="h-3.5 w-3.5 shrink-0 text-muted-foreground" aria-hidden="true" />
              <span className={cn("flex-1 text-foreground", d === "reject" && "text-muted-foreground line-through")}>
                {item.label}
              </span>
              {d === "approve" && (
                <>
                  <Check className="h-4 w-4 shrink-0 text-[color:var(--accent-emerald)]" aria-hidden="true" />
                  <span className="sr-only">approved</span>
                </>
              )}
              {d === "reject" && (
                <>
                  <X className="h-4 w-4 shrink-0 text-[color:var(--accent-rose)]" aria-hidden="true" />
                  <span className="sr-only">rejected</span>
                </>
              )}
              {!d && isActive && (
                <div className="flex shrink-0 gap-1.5">
                  <button
                    type="button"
                    autoFocus={autoFocus}
                    disabled={busy}
                    onClick={() => decide(item.id, "approve")}
                    aria-label={`Approve ${item.label}`}
                    className={cn(
                      "rounded-md bg-[color:var(--accent-emerald)]/10 px-2 py-1 text-[color:var(--accent-emerald)] hover:bg-[color:var(--accent-emerald)]/20 disabled:opacity-50",
                      motion,
                      focusRing,
                    )}
                  >
                    <Check className="h-3 w-3" aria-hidden="true" />
                  </button>
                  <button
                    type="button"
                    disabled={busy}
                    onClick={() => decide(item.id, "reject")}
                    aria-label={`Reject ${item.label}`}
                    className={cn(
                      "rounded-md bg-[color:var(--accent-rose)]/10 px-2 py-1 text-[color:var(--accent-rose)] hover:bg-[color:var(--accent-rose)]/20 disabled:opacity-50",
                      motion,
                      focusRing,
                    )}
                  >
                    <X className="h-3 w-3" aria-hidden="true" />
                  </button>
                </div>
              )}
            </li>
          );
        })}
      </ol>
      <InlineError message={error} />
      {allowUndo && current > 0 && (
        <div className="flex justify-end border-t border-border px-3 py-1.5">
          <button type="button" onClick={undoLast} className={cn(btnLink, "inline-flex items-center gap-1")}>
            <RotateCcw className="h-2.5 w-2.5" aria-hidden="true" />
            undo last
          </button>
        </div>
      )}
    </div>
  );
}

export const DEMO_BATCH: BatchQueueEvent = {
  kind: "batch.queue",
  id: "demo-batch",
  items: [
    { id: "b1", kind: "search", label: "Run refined search for “carbon pricing”" },
    { id: "b2", kind: "research", label: "Add 3 sources to workspace" },
    { id: "b3", kind: "write", label: "Update Section 2 with citations" },
    { id: "b4", kind: "read", label: "Read ec.europa.eu/clima/ets" },
    { id: "b5", kind: "write", label: "Draft 800-word summary" },
  ],
};
