/**
 * hitl-sync.mjs — akaoss's copy of the HITL Kit primitives, generated.
 *
 * The primitives live in the HITL-KIT repo as `@hitl-kit/ui`
 * (hitl-ai2/packages/ui). This site does not hand-maintain a second copy:
 * everything under `src/components/hitl/`, everything under `public/r/`, and
 * `src/lib/registry-items.ts` is produced by this script, and
 * `pnpm hitl:check` fails CI if any of it has drifted. Same contract as
 * `facts.json`.
 *
 * Two stages, so the check works with or without the library checkout:
 *
 *   1. PULL (needs HITL_KIT_DIR, default ../hitl-ai2): copy the package's
 *      generated registry JSON into `public/r/`, and vendor core's event and
 *      action sources under `src/components/hitl/core/` (until
 *      `@hitl-kit/core` 0.6 is on npm).
 *   2. DERIVE (always): regenerate `src/components/hitl/*` and
 *      `src/lib/registry-items.ts` from `public/r/*.json`, rewriting the
 *      `@hitl-kit/core` import to the vendored copy.
 *
 * In CI there is no sibling checkout, so stage 1 is skipped and the check
 * proves the three generated surfaces agree with each other. Freshness
 * against the library is the developer's job: run `pnpm hitl:sync` after
 * building the registry there, and commit.
 *
 *   pnpm hitl:sync    regenerate (pull if the kit is present, then derive)
 *   pnpm hitl:check   regenerate, then fail on git drift
 */

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SITE = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const KIT = resolve(SITE, process.env.HITL_KIT_DIR ?? "../hitl-ai2");
const UI_REGISTRY = join(KIT, "packages", "ui", "registry");
const CORE = join(KIT, "packages", "core", "src");
const CHECK = process.argv.includes("--check");
const OFFLINE = process.argv.includes("--offline") || !existsSync(join(UI_REGISTRY, "registry.json"));

const OUT_COMPONENTS = join(SITE, "src", "components", "hitl");
const OUT_REGISTRY = join(SITE, "public", "r");
const OUT_ITEMS = join(SITE, "src", "lib", "registry-items.ts");

const BANNER =
  "// GENERATED by `pnpm hitl:sync` from @hitl-kit/ui (hitl-ai2/packages/ui). Do not edit; edit the package.\n";

function write(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

function banner(source) {
  // Keep the "use client" directive first; the banner goes right after it.
  if (source.startsWith('"use client";')) {
    return '"use client";\n' + BANNER + source.slice('"use client";'.length).replace(/^\n/, "");
  }
  return BANNER + source;
}

// ── 1. PULL: registry JSON and vendored core from the library checkout ───────
if (OFFLINE) {
  console.log(
    process.argv.includes("--offline")
      ? "· hitl-sync: offline; deriving from public/r only"
      : `· hitl-sync: library checkout not found at ${KIT}; deriving from public/r only`,
  );
} else {
  rmSync(OUT_REGISTRY, { recursive: true, force: true });
  mkdirSync(OUT_REGISTRY, { recursive: true });
  let r = 0;
  for (const file of readdirSync(UI_REGISTRY)) {
    if (!file.endsWith(".json")) continue;
    writeFileSync(join(OUT_REGISTRY, file), readFileSync(join(UI_REGISTRY, file)));
    r++;
  }
  rmSync(join(OUT_COMPONENTS, "core"), { recursive: true, force: true });
  for (const f of ["events.ts", "actions.ts"]) {
    write(join(OUT_COMPONENTS, "core", f), BANNER + readFileSync(join(CORE, f), "utf8"));
  }
  write(join(OUT_COMPONENTS, "core", "index.ts"), BANNER + 'export * from "./events";\nexport * from "./actions";\n');
  console.log(`· hitl-sync: pulled ${r} registry files and core from ${KIT}`);
}

// ── 2. DERIVE: components and the catalogue list from public/r ───────────────
const indexPath = join(OUT_REGISTRY, "registry.json");
if (!existsSync(indexPath)) {
  console.error("✗ hitl-sync: public/r/registry.json missing. Run with the library checkout present.");
  process.exit(1);
}
const index = JSON.parse(readFileSync(indexPath, "utf8"));

// Everything except the vendored core is regenerated from scratch.
if (existsSync(OUT_COMPONENTS)) {
  for (const entry of readdirSync(OUT_COMPONENTS)) {
    if (entry === "core") continue;
    rmSync(join(OUT_COMPONENTS, entry), { recursive: true, force: true });
  }
}

let n = 0;
for (const item of index.items) {
  const full = JSON.parse(readFileSync(join(OUT_REGISTRY, `${item.name}.json`), "utf8"));
  for (const f of full.files) {
    if (!f.target.startsWith("components/hitl/")) continue; // lib/utils.ts is the site's own
    const rel = f.target.slice("components/hitl/".length);
    const source = f.content.replace(/from "@hitl-kit\/core"/g, 'from "@/components/hitl/core"');
    write(join(OUT_COMPONENTS, rel), banner(source));
    n++;
  }
}

const short = (url) => url.replace(/^.*\/r\//, "").replace(/\.json$/, "");
const items = index.items.map((i) => ({
  name: i.name,
  title: i.title,
  description: i.description,
  type: i.type,
  ...(i.registryDependencies ? { registryDependencies: i.registryDependencies.map(short) } : {}),
}));
write(
  OUT_ITEMS,
  BANNER +
    `export interface RegistryItem {
  name: string;
  title: string;
  description: string;
  type: "registry:ui" | "registry:lib";
  registryDependencies?: string[];
}

export const REGISTRY_ITEMS: RegistryItem[] = ${JSON.stringify(items, null, 2)};

export const REGISTRY_BASE_URL = "https://www.hitlkit.dev/r";
`,
);

console.log(`· hitl-sync: ${n} component files and ${items.length} catalogue items derived from public/r`);

// ── 3. CHECK ────────────────────────────────────────────────────────────────
if (CHECK) {
  const paths = ["src/components/hitl", "public/r", "src/lib/registry-items.ts"];
  try {
    execFileSync("git", ["diff", "--exit-code", "--", ...paths], { cwd: SITE, stdio: "inherit" });
    const untracked = execFileSync("git", ["ls-files", "--others", "--exclude-standard", "--", ...paths], {
      cwd: SITE,
      encoding: "utf8",
    }).trim();
    if (untracked) throw new Error(`untracked:\n${untracked}`);
    console.log("✓ hitl up to date");
  } catch (e) {
    console.error(
      "\n✗ HITL DRIFT — the generated primitives differ from the committed copy.\n" +
        "  Run `pnpm hitl:sync` (with ../hitl-ai2 checked out and its registry built) and commit.",
    );
    if (e instanceof Error && e.message.startsWith("untracked")) console.error(e.message);
    process.exit(1);
  }
}
