/**
 * hitl-sync.mjs — akaoss's copy of the HITL Kit primitives, generated.
 *
 * The primitives live in the HITL-KIT repo as `@hitl-kit/ui`
 * (hitl-ai2/packages/ui). This site does not hand-maintain a second copy:
 * everything under `src/components/hitl/`, everything under `public/r/`, and
 * `src/lib/registry-items.ts` is produced by this script from the package
 * source, and `pnpm hitl:check` fails CI if any of it has drifted. Same
 * contract as `facts.json`.
 *
 * Until `@hitl-kit/ui` and `@hitl-kit/core` 0.6 are on npm, the source is the
 * sibling checkout (HITL_KIT_DIR, default ../hitl-ai2). Core's event and
 * action sources are vendored under `src/components/hitl/core/` and the
 * `@hitl-kit/core` import is rewritten to point at them; the registry JSON
 * served from /r keeps the real `@hitl-kit/core` dependency.
 *
 *   pnpm hitl:sync    regenerate
 *   pnpm hitl:check   regenerate, then fail on git drift
 */

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SITE = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const KIT = resolve(SITE, process.env.HITL_KIT_DIR ?? "../hitl-ai2");
const UI = join(KIT, "packages", "ui");
const CORE = join(KIT, "packages", "core", "src");
const CHECK = process.argv.includes("--check");

const OUT_COMPONENTS = join(SITE, "src", "components", "hitl");
const OUT_REGISTRY = join(SITE, "public", "r");
const OUT_ITEMS = join(SITE, "src", "lib", "registry-items.ts");

for (const p of [join(UI, "registry.json"), join(UI, "registry", "registry.json"), join(CORE, "events.ts"), join(CORE, "actions.ts")]) {
  if (!existsSync(p)) {
    console.error(`✗ hitl-sync: ${p} not found. Set HITL_KIT_DIR to the HITL-KIT checkout and run its \`pnpm --filter @hitl-kit/ui registry:build\`.`);
    process.exit(1);
  }
}

const manifest = JSON.parse(readFileSync(join(UI, "registry.json"), "utf8"));

const BANNER =
  "// GENERATED by `pnpm hitl:sync` from hitl-ai2/packages/ui (@hitl-kit/ui). Do not edit; edit the package.\n";

/** Package-relative specifier → this site's aliases. Longest first. */
const REWRITES = [
  [/from "\.\.\/lib\/utils"/g, 'from "@/lib/utils"'],
  [/from "\.\/lib\/utils"/g, 'from "@/lib/utils"'],
  [/from "\.\/internal\/ui"/g, 'from "@/components/hitl/internal/ui"'],
  [/from "\.\/([A-Za-z-]+)"/g, 'from "@/components/hitl/$1"'],
  [/from "@hitl-kit\/core"/g, 'from "@/components/hitl/core"'],
];

function rewrite(source) {
  return REWRITES.reduce((s, [re, to]) => s.replace(re, to), source);
}

function banner(source) {
  // Keep the "use client" directive first; the banner goes right after it.
  if (source.startsWith('"use client";')) {
    return '"use client";\n' + BANNER + source.slice('"use client";'.length).replace(/^\n/, "");
  }
  return BANNER + source;
}

function write(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

// ── 1. Components ─────────────────────────────────────────────────────────────
rmSync(OUT_COMPONENTS, { recursive: true, force: true });
let n = 0;
for (const item of manifest.items) {
  for (const f of item.files) {
    if (f.path === "lib/utils.ts") continue; // the site owns its own cn()
    const rel = f.target.replace(/^components\/hitl\//, "");
    write(join(OUT_COMPONENTS, rel), banner(rewrite(readFileSync(join(UI, "src", f.path), "utf8"))));
    n++;
  }
}

// ── 2. Vendored core (events + actions), until @hitl-kit/core 0.6 is on npm ──
for (const f of ["events.ts", "actions.ts"]) {
  write(join(OUT_COMPONENTS, "core", f), BANNER + readFileSync(join(CORE, f), "utf8"));
}
write(
  join(OUT_COMPONENTS, "core", "index.ts"),
  BANNER + 'export * from "./events";\nexport * from "./actions";\n',
);

// ── 3. Registry JSON served from /r ───────────────────────────────────────────
rmSync(OUT_REGISTRY, { recursive: true, force: true });
mkdirSync(OUT_REGISTRY, { recursive: true });
let r = 0;
for (const file of readdirSync(join(UI, "registry"))) {
  if (!file.endsWith(".json")) continue;
  writeFileSync(join(OUT_REGISTRY, file), readFileSync(join(UI, "registry", file)));
  r++;
}

// ── 4. The catalogue's item list ──────────────────────────────────────────────
const short = (url) => url.replace(/^.*\/r\//, "").replace(/\.json$/, "");
const items = manifest.items.map((i) => ({
  name: i.name,
  title: i.title,
  description: i.description,
  type: i.type,
  ...(i.registryDependencies ? { registryDependencies: i.registryDependencies.map(short) } : {}),
}));
write(
  OUT_ITEMS,
  BANNER +
    `export interface RegistryItem {
  name: string;
  title: string;
  description: string;
  type: "registry:ui" | "registry:lib";
  registryDependencies?: string[];
}

export const REGISTRY_ITEMS: RegistryItem[] = ${JSON.stringify(items, null, 2)};

export const REGISTRY_BASE_URL = "https://www.hitlkit.dev/r";
`,
);

console.log(`· hitl-sync: ${n} component files, core vendored, ${r} registry files, ${items.length} catalogue items`);

if (CHECK) {
  const paths = ["src/components/hitl", "public/r", "src/lib/registry-items.ts"];
  try {
    execFileSync("git", ["diff", "--exit-code", "--", ...paths], { cwd: SITE, stdio: "inherit" });
    const untracked = execFileSync("git", ["ls-files", "--others", "--exclude-standard", "--", ...paths], {
      cwd: SITE,
      encoding: "utf8",
    }).trim();
    if (untracked) throw new Error(`untracked:\n${untracked}`);
    console.log("✓ hitl up to date");
  } catch (e) {
    console.error("\n✗ HITL DRIFT — the generated primitives differ from the committed copy. Run `pnpm hitl:sync` and commit.");
    if (e instanceof Error && e.message.startsWith("untracked")) console.error(e.message);
    process.exit(1);
  }
}
