#!/usr/bin/env node
/**
 * structure-check.mjs: the repo layout, stated as rules a script can check.
 *
 * akaoss is a plain Next.js App Router site. Routes under `app/` hold
 * metadata, the shell and imports; the sections a page composes live in
 * `components/features/<area>/`; shared vocabulary in `components/ui/`; the
 * marks in `components/brand/`; data and loaders in `lib/`. Three surfaces
 * are generated by `pnpm hitl:sync` and exempt from naming rules:
 * `components/hitl/`, `public/r/`, `lib/registry-items.ts`.
 *
 * Rules (see docs/superpowers/specs/2026-09-02-site-structure-design.md):
 *   root-layout                  app/, components/, lib/ at the root; no src/
 *   no-route-private-components  no `_components/` under app/
 *   no-app-imports               components/ and lib/ never import @/app/
 *   lib-imports-ui               lib/ never imports @/components/
 *   no-barrels                   no index.ts(x) under components/ or lib/
 *   kebab-case                   file basenames are kebab-case
 *   no-parent-imports            no import path starts with ../
 *   pages-compose                page.tsx and layout.tsx are never "use client"
 *
 *   pnpm structure:check
 */

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { basename, dirname, extname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED = ["components/hitl/"];
const SOURCE_EXT = new Set([".ts", ".tsx", ".css", ".mjs"]);
const KEBAB = /^[a-z0-9]+(-[a-z0-9]+)*(\.[a-z0-9]+)*\.(ts|tsx|css|mjs)$/;

const problems = [];
const fail = (rule, path, detail) =>
  problems.push(`${rule.padEnd(28)} ${path}${detail ? `  (${detail})` : ""}`);

function walk(dir, out = []) {
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

const rel = (p) => relative(ROOT, p).split("\\").join("/");
const isGenerated = (r) => GENERATED.some((g) => r.startsWith(g));
const isRouteFile = (r) => /^app\/(.*\/)?(page|layout)\.tsx$/.test(r);

// root-layout
for (const d of ["app", "components", "lib"]) {
  if (!existsSync(join(ROOT, d))) fail("root-layout", `${d}/`, "missing");
}
if (existsSync(join(ROOT, "src"))) {
  fail("root-layout", "src/", "app/, components/ and lib/ live at the root");
}

const files = ["app", "components", "lib"]
  .flatMap((d) => walk(join(ROOT, d)))
  .map(rel)
  .filter((r) => SOURCE_EXT.has(extname(r)))
  .sort();

for (const r of files) {
  const generated = isGenerated(r);
  const source = readFileSync(join(ROOT, r), "utf8");
  const imports = [...source.matchAll(/\bfrom\s+["']([^"']+)["']/g), ...source.matchAll(/^\s*import\s+["']([^"']+)["']/gm)].map((m) => m[1]);

  if (r.startsWith("app/") && r.split("/").includes("_components")) {
    fail("no-route-private-components", r, "move to components/features/<area>/");
  }
  if (!generated && /(^|\/)index\.tsx?$/.test(r)) {
    fail("no-barrels", r, "import the file, not the folder");
  }
  if (!generated && !KEBAB.test(basename(r))) {
    fail("kebab-case", r);
  }
  if (!r.startsWith("app/") && imports.some((i) => i.startsWith("@/app/"))) {
    fail("no-app-imports", r, "components/ and lib/ never reach into app/");
  }
  if (r.startsWith("lib/") && imports.some((i) => i.startsWith("@/components/"))) {
    fail("lib-imports-ui", r, "data does not depend on UI");
  }
  if (!generated && imports.some((i) => i.startsWith("../"))) {
    fail("no-parent-imports", r, "siblings use ./, everything else uses @/");
  }
  if (isRouteFile(r) && /^\s*["']use client["']/m.test(source)) {
    fail("pages-compose", r, "client leaves belong in components/");
  }
}

if (problems.length) {
  console.error(`✗ structure: ${problems.length} problem${problems.length === 1 ? "" : "s"}\n`);
  for (const p of problems) console.error(`  ${p}`);
  console.error("\n  Rules: docs/superpowers/specs/2026-09-02-site-structure-design.md");
  process.exit(1);
}
console.log(`✓ structure ok (${files.length} files)`);
